# API and Market settings
api:
  user: 'Global'
  password: '205225240236229161211244239242237183223195239230230229229198236239239242'

settings:
  resolution: "hourly"
  timezone: "UTC"
  currency: "EUR"