defaults:
  - api: default
  - data: default
  - model: lstm
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

paths:
  models_dir: models
  outputs_dir: outputs

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: null
  job:
    chdir: false



target: level        # or spread
dataset: core_20200101_20251231
horizon: 24          # forecast horizon H